[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "api.peachplanner.com"

[context."develop".environment]
  NEXT_PUBLIC_API_URL = "peach-planner-server.herokuapp.com"
