### signup user - email 바꾸면서 가야함
POST https://api.peachplanner.com/api/auth/signup
Content-Type: application/json

{
  "email": "test_user111@peach_planner.com",
  "name": "테스트유저",
  "nickName": "테스트유저선명",
  "password": 1234,
  "profilePath": "https://peach-planner-static.s3.ap-northeast-2.amazonaws.com/peachplanner/peach_planner_user_deafult.png",
  "tel": "000-1111-1111",
  "type": "USER",
  "userName": "test_user111@peach_planner.com"
}

### signup planner - email 바꾸면서 가야함

POST https://api.peachplanner.com/api/auth/signup
Content-Type: application/json

{
  "email": "test_planner111@peach_planner.com",
  "name": "테스트유저",
  "nickName": "기연333",
  "password": 1234,
  "profilePath": "https://peach-planner-static.s3.ap-northeast-2.amazonaws.com/peachplanner/peach_planner_user_deafult.png",
  "tel": "000-1111-1111",
  "type": "PLANNER",
  "userName": "test_planner111@peach_planner.com"
}
