POST https://api.peachplanner.com/api/auth/login
Content-Type: application/json

{
    "loginType": "BASIC",
    "password": 1234,
    "userName": "test@test.com"
}

###
GET https://api.peachplanner.com/api/users/me
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI5NCIsImlhdCI6MTY0MDM0MzIxMCwiZXhwIjoxNjQwNDI5NjEwfQ.K7OY_Rz2EQV3n0T13c2VyRkjiRZOUJ5GzJVTbEJGNPq3XiWRDy7uao5KDaQw546p
